Aggiunta commenti e modifica messaggio in remove

diff --git a/init_repo b/init_repo
--- a/init_repo
+++ b/init_repo
@@ -5,7 +5,7 @@ function create_dir {
 		echo "Directory \"$1\" already exists."	# there's nothing to do
 	else
 		mkdir "$1"		# otherwise, it creates the directory
-		if [ $? -eq 0 ]; then	# if the exit code of mkdir is equal to 0
+		if [ $? -eq 0 ]; then	# if the exit code of mkdir is equal to 0 (no errors)
 			echo "Directory \"$1\" has been successfully created."
 		fi
 	fi
diff --git a/remove b/remove
--- a/remove
+++ b/remove
@@ -1,9 +1,9 @@
 #!/bin/bash
 
 function remove_file {
-	if [ -f "$1" ]; then
-		rm -f "$1"  #-f per forzare rimozione
-		if [ $? -eq 0 ]; then
+	if [ -f "$1" ]; then		# if the passed file exists
+		rm -f "$1"		# deletes the file without prompt
+		if [ $? -eq 0 ]; then	# if the exit code of rm is equal to 0 (no errors)
 			echo "$2 copy of file has been successfully removed."
 		fi
 	else
@@ -13,19 +13,19 @@ function remove_file {
 }
 
 
-if [ -z "$2" ]; then
+if [ -z "$2" ]; then		# if <file name> argument is an empty string
   	echo "Usage: remove <repo> <file name>"
 	exit
 fi
 
-backup_dir=".$1.bck"
-working_copy="$1/$2"
-backup_copy="$backup_dir/$2"
+backup_dir=".$1.bck"		# repository backup directory
+working_copy="$1/$2"		# working copy of file to delete
+backup_copy="$backup_dir/$2"	# backup copy of file to delete
 
-if [ ! -d "$backup_dir" ]; then
-	echo "Repository \"$1\" does not exist."
+if [ ! -d "$backup_dir" ]; then		# if the backup directory of the specified repository does not exist
+	echo "Repository \"$1\" does not exist or has not been initialized."
 	exit
 fi
 
-remove_file "$working_copy" "Working"
-remove_file "$backup_copy" "Backup"
+remove_file "$working_copy" "Working"		# calls remove_file to delete the working copy
+remove_file "$backup_copy" "Backup"		# calls remove_file to delete the backup copy
